language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: K73ylChK9cbfeX4m1uXu5yRcNzBglvssjjNw6U9bSjS/NXmOtuVT1lyXw+BGRR5LHIN3Pt1YT1GPNZC4MOuvxmZnvIXQOXbXHqgcnH5E+CHxM2udd8ho0ozOoEG56ly4U467rqZlrzLPxkzWyfmGJNgP4WOOKeKGf15HlKaNO/dmPiZWkBY6d/D4DTaaWzoFoFy7YaAqJ8vGRrvQV6gVQV5AXdUIlEsCIWoVaEO3QfTTVC8/yskhw4Z+V77NCsjzAxDF00yKg/cRxFhNUK4UAbQHZ/7x8rZliU9+eyLuYI+9FqgO6irLwUD6KhmDd5Sa9TxY7mSYLlWzoikRRLDfVFn9lbCB7XeX4xZVgF//kp2nCGISrlg7cr5ZwTYYeuwub/p2LMNZVxUsU46OSCaLWpbQS4oOH3uWXe7ZruJvJasfpJPui+IhwVZ3u4rTe2GyRg4QeEa4wzVDld32HRSib4nO2i6ZfcY3rNMOVTT2rx7nNS9nwMCVXF9hZqVnX05/wRQyd0KfW5C2ka9AL6YtoXW11+03LYifqpJ/BpJJybQR3Bwhp/OrKomK6gM3Swf4JM5NysCgMnqCoSinCW53wkMNbH4lh25Fsv0xArxEB3jCgc1PDhoOodADQkJ0KC3LFlE1Z2D+is2WqKbJ0LhqpTkPFIqkNjxdVrv+0SNwNyA=
  email: false
after_success:
- sh ./scripts/publish-docs.sh
- npm run coverage
env:
  matrix:
    secure: cD13a4I8Ge06sKkvOzvXLNWnMEOHNIT/YjRhq64gofsdno7+N/pj22aLgFKUZMwcLATu9OrGDFb7u17zRQ9Uct6Cks5gvY8NWevFzU6LzaV3gPh8QQ4DSE47zDhBr7CzURFL3xD6gnMbtQEq4/IS6puUKmxqNGO9/1QjBqzAbPfH0fL6FhdoT64tZkV6Xjmsr+NzmEtsHyKMABTdWv0vUin1IOEHxqj5VH3LhTANieLLvNQ028Vz2nnWaFsNaoNZUUWuXVoTf6b+zCnFDv2UEa5RoScjro0PBqx7F+5kEVwWBnS2U8SMamonPXGIirPNGsl4KnNQBsKYE4x4jYgy7rDsexFCKFKfpNzF4oTkIy0trDRHY62fhdTOETnDPhVQ7+eBNmVBJpltfuL8l9Galv6cElFZWGyxepW9Ke/Tpf2m1dU01t7L7kyyuF1wZAPTEHnXpUPimFiWXXAvRi0jmxOXRqSESGOiQxqH8K0BwUsQ7oMeUx95VugzlNQAypJZ+aIyVqlWx4l9yXjEQa6UXAq7DbML1+OST2Nwcs3M3PGX/fbAjCLzYnvrLs1NonBR614K8CuA118LJETvOaFzOtj9HmlDSNptiPg0Fa2jtCCtpmHi1X+IDFGb03sp6rjOPryKT67QTmMfRIjRf3/k+vQBV8TKY6WbxNKG9k3Dq2M=
